### ISSUE TITLE
Don't hard code "C:" drive.

### ISSUE THREAD

**Issue by vadz** [google/UIforETW#8] opened 2015-04-15 12:40 UTC
The program refuses to start up on my machine where the Windows drive is "W:" and not "C:" because of the hard coded "C:" at

https://github.com/google/UIforETW/blob/cf3f8ee9c5d3d4014f93481c5bff0c6048f45c77/UIforETW/UIforETWDlg.cpp#L297

The code should really use `SHGetKnownFolderPath()`.

**Comment by randomascii** [comment] 2015-04-15 20:52
Confirmed. And easy to fix.

**Comment by randomascii** [comment] 2015-04-16 05:55
Fixed with change 5ce43384dc0ed13196ab3712caf9c31f1c6350cb, which removes all hard-coded references to C:.

Note that for now you'll have to build from source to get this fix. Binary releases are intended to be less common.

**Closed by randomascii** 2015-04-16 05:55 UTC

**Comment by randomascii** [comment] 2015-04-16 06:02
Fixed fix in change 408ed3a6fe0e6b003b3f71963dc25e4e26611a01. Now all is well.
